# Generated by Django 3.0.2 on 2020-05-01 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200501_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pruduct_name',
            new_name='product_name',
        ),
    ]
