# Generated by Django 3.0.2 on 2020-05-02 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200502_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='color_quantity',
        ),
    ]
