# Generated by Django 3.0.2 on 2020-05-02 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_color_color_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_color',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.Color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.Category'),
        ),
    ]
