# Generated by Django 3.0.2 on 2020-05-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200502_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='category_id',
            field=models.IntegerField(default=0),
        ),
    ]
