# Generated by Django 3.0.2 on 2020-05-02 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_subcategory_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category_id',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.Category'),
        ),
    ]
