# Generated by Django 3.0.2 on 2020-05-02 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200502_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superCategory_name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_subCategory',
        ),
        migrations.AddField(
            model_name='category',
            name='superCategory_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.Category'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
